name: Build and Push Jekyll Site
on:
  push:
    branches: ["master"]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Build Jekyll
        run: |
          gem install jekyll bundler
          # 强制编译到根目录，这样 CF 搬运工就能看见
          bundle exec jekyll build --destination ./dist
      - name: Deploy to Master
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # 只把 dist 里的成品发出去
          git add -f dist/
          git commit -m "Deploy site" || exit 0
          git push origin master
