name: Zero-Dependency-Build
on:
  push:
    branches: ["master"]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install and Build
        run: |
          gem install jekyll jekyll-theme-minimal
          jekyll build
          # 这一步非常关键：把生成的 _site 变出来给 CF 看
          cp -r _site dist
      - name: Push to Repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -f dist/
          git commit -m "Force deploy to dist" || exit 0
          git push origin master
